
---
include:
 # - board: eyelash_sofle_left
#    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view_custom urchin_left nice_view_adapter
  - board: eyelash_sofle_left
    shield: nice_view urchin_left nice_view_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
