manifest:
  remotes:
      # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urchin-peripheral-animation                         #new entry
      url-base: https://github.com/superlarps/urchin-peripheral-animation.git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: urchin-peripheral-animation   #new entry
      remote: superlarps
      revision: main                      #new entry
  self:
    path: config
